name: Publish Demo
on:
  workflow_dispatch:
    inputs:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        env:
          AOC_YEAR: 2020
          AOC_BOARD: 5017
          AOC_INCLUDE: 384199
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
          GRIDSOME_PATH_PREFIX: /AdventOfCodeDashboard
          AOC_REPOS: ["https://raw.githubusercontent.com/EldoranDev/AdventOfCode/main/aoc-repo.json"]
        run: |
          npm ci 
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: GH-Actions
          GIT_CONFIG_EMAIL: "@actions"
